[meta title:"Web" description:"Short description of your project" /]

[var name:"state" value:0 /]

[Waypoint onEnterView:`state = 0`]
[section]
    [Header
      title:"Ngorongoro Flood Refugee Plan"
      subtitle:"Prepared for the United Nations High Commissioner for Refugees"
      author:"Creative Goodwill Co."
      authorLink:"http://creativegoodwill.co" /]
[/section]
[/Waypoint]



[Waypoint onEnterView:`state = 0`]
    On 20 April 2017, heavy rains fell on the northern territory of Tanzania.
[/Waypoint]

[Waypoint onEnterView:`state = 1`]
    Many areas were affected, but the village of Endulen was devastated.
[/Waypoint]

[Waypoint onEnterView:`state = 2`]
    [section]
        For 3 days Endulen was hit with storm waters which accumulated to 500mm of flood water on April 23.
    [/section]
[/Waypoint]
[Waypoint onEnterView:`state = 3`]
    [section]
        1,000 people were affected with 500 people needing immediate shelter assistance.
    [/section]
[/Waypoint]
[Waypoint onEnterView:`state = 4`]
    [section]
        The 500 Maasai in need of shelter will be relocated to a relief site outside the Maswa Game Reserve
    [/section]
[/Waypoint]
[Waypoint onEnterView:`state = 5`]
    [section]
        The relief site will be composed of 80 shelters with an average of 7 refugees per shelter.

        The relief site respects the traditional layout of Masaai villages: it uses a circular pattern for its layout and dome-shaped shelters.
    [/section]
[/Waypoint]

[Fixed]
[FullScreen]
    [GraphicComponent state:state/]
[/FullScreen]
[/Fixed]
