[meta title:"Web" description:"Short description of your project" /]

[var name:"state" value:0 /]

[Waypoint onEnterView:`state = 0`]
[section]
    [Header
      title:"Ngorongoro Flood Refugee Plan"
      subtitle:"Prepared for the United Nations High Commissioner for Refugees"
      author:"Creative Goodwill Co."
      authorLink:"http://creativegoodwill.co" /]
[/section]
[/Waypoint]



[Waypoint onEnterView:`state = 0`]
    On 20 April 2017, heavy rains fell on the northern territory of Tanzania.
[/Waypoint]

[Waypoint onEnterView:`state = 1`]
    Village of Endulen was devastated.
[/Waypoint]

[Waypoint onEnterView:`state = 2`]
    [section]
        For 3 days the village of Endulen was hit with water which accumulated to 500mm of flood water on April 23.
    [/section]
[/Waypoint]
[Waypoint onEnterView:`state = 3`]
    [section]
        1,000 people were affected with 500 people needing immediate shelter assistance.
    [/section]
[/Waypoint]
[Waypoint onEnterView:`state = 4`]
    [section]
        We will relocate them to a relief site outside the Maswa Game Reserve
    [/section]
[/Waypoint]
[Waypoint onEnterView:`state = 5`]
    [section]
        The site layout
    [/section]
[/Waypoint]

[Fixed]
[FullScreen]
    [GraphicComponent state:state/]
[/FullScreen]
[/Fixed]
